baseURL = "https://www.wangfujie.site/"
title = "WangFuJie Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "zh-cn"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "G-W7C8VSVJJJ"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination  # 首页每页显示的文章数
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "王富杰的博客 | WangFuJie Blog"
  description = "王富杰，程序员, DBA, 开源爱好者，生活探险家 | 这里是 王富杰 的博客，与你一起发现更大的世界。"
  keyword = "王富杰, wangfujie, Wangfujie, , 王富杰的网络日志, 王富杰的博客, Wangfujie Blog, 博客, 个人网站, 互联网, DBA, Python, MySQL"
  slogan = "路在脚下，心向远方"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = "Z50MGWBPZX"
  algolia_indexName = "wangfujie_blog"
  algolia_apiKey = "3df8455fd3504e5295835ff1e1cbc0b2"

  # Sidebar settings
  sidebar_about_description = "DBA, OP, Software Developer, Open Source Enthusiast"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/wangfujie.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  # 显示文档标签列表，如果包含标签的文档大于0即显示
  featured_tags = true 
  featured_condition_size = 0 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  # 这个评论依赖monogo数据库且免费只有500M,这里暂时废弃
  # twikoo_env_id = "https://comment.wangfujie.site/"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "wfjaizwj@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "https://x.com/home"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  stackoverflow  = "https://stackoverflow.com/users/25345798/fujie-wang"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/wang-fu-jie"
  wechat         = "img/wechat_qrcode.jpg"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "我的博客园"
  href =  "https://www.cnblogs.com/jkin"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "归档"
  href =  "/archive/"
  

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[params.giscus]
  data_repo="wang-fu-jie/blog"
  data_repo_id="R_kgDOMC8zKA"
  data_category="Announcements"
  data_category_id="DIC_kwDOMC8zKM4Cko6y"
  data_mapping="pathname"
  data_strict="0"
  data_reactions_enabled="1"
  data_emit_metadata="0"
  data_theme="preferred_color_scheme"
  data_lang="zh-CN"
  crossorigin="anonymous"


[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"


[permalinks]
  post = "/:year/:month/:day/:slug/"
